# Generated by Django 3.2.7 on 2021-10-03 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('calories_per_100_gr', models.PositiveIntegerField()),
                ('protein_per_100_gr', models.PositiveIntegerField()),
                ('fat_per_100_gr', models.PositiveIntegerField()),
                ('carbohydrates_per_100_gr', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('how_to_cook', models.TextField()),
                ('for_how_many_persons', models.PositiveSmallIntegerField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingredients_and_recipes.recipecategory')),
                ('ingredient_quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients_and_recipes.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_gr', models.PositiveIntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients_and_recipes.ingredient')),
            ],
        ),
    ]
