# Generated by Django 3.2.7 on 2022-03-12 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('calories_per_100_gr', models.PositiveIntegerField(blank=True, null=True)),
                ('protein_per_100_gr', models.PositiveIntegerField(blank=True, null=True)),
                ('fat_per_100_gr', models.PositiveIntegerField(blank=True, null=True)),
                ('carbohydrates_per_100_gr', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_gr', models.PositiveIntegerField()),
                ('measure', models.CharField(blank=True, max_length=255)),
                ('annotation', models.CharField(blank=True, max_length=255)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients_and_recipes.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('eng_name', models.CharField(blank=True, max_length=255, null=True)),
                ('how_to_cook', models.TextField()),
                ('for_how_many_persons', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ingredient_quantity', models.ManyToManyField(to='ingredients_and_recipes.IngredientQuantity', verbose_name='list of ingredients')),
            ],
        ),
    ]
