# Generated by Django 3.2.7 on 2022-04-10 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('calories_per_100_gr', models.PositiveIntegerField(blank=True, null=True)),
                ('protein_per_100_gr', models.PositiveIntegerField(blank=True, null=True)),
                ('fat_per_100_gr', models.PositiveIntegerField(blank=True, null=True)),
                ('carbohydrates_per_100_gr', models.PositiveIntegerField(blank=True, null=True)),
                ('cup250sm', models.FloatField(blank=True, null=True)),
                ('bigspoon', models.FloatField(blank=True, null=True)),
                ('littlespoon', models.FloatField(blank=True, null=True)),
                ('onepiece', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('measure', models.CharField(choices=[('стак.', 'стак.'), ('ст.л.', 'ст.л.'), ('чл.', 'ч.л.'), ('гр.', 'гр.'), ('кг.', 'кг.'), ('шт.', 'шт.'), ('пуч.', 'пуч.'), ('зуб.', 'зуб.'), ('щепотк.', 'щепотк.'), ('л.', 'л.'), ('мл.', 'мл.'), ('ломт.', 'ломт'), ('гол.', 'гол.'), ('вет.', 'вет.')], max_length=255)),
                ('annotation', models.CharField(blank=True, max_length=255)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients_and_recipes.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('eng_name', models.CharField(blank=True, max_length=255, null=True)),
                ('how_to_cook', models.TextField()),
                ('for_how_many_persons', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ingredient_quantity', models.ManyToManyField(to='ingredients_and_recipes.IngredientQuantity', verbose_name='list of ingredients')),
            ],
        ),
    ]
