# Generated by Django 3.2.7 on 2021-10-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients_and_recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient_quantity',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient_quantity',
            field=models.ManyToManyField(to='ingredients_and_recipes.IngredientQuantity', verbose_name='list of ingredients'),
        ),
    ]
