# Generated by Django 3.2.7 on 2022-02-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients_and_recipes', '0002_auto_20211004_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientquantity',
            name='annotation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ingredientquantity',
            name='measure',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
