# Generated by Django 3.2.7 on 2022-03-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients_and_recipes', '0002_auto_20220322_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientquantity',
            name='quantity_gr',
        ),
        migrations.AddField(
            model_name='ingredientquantity',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredientquantity',
            name='measure',
            field=models.CharField(choices=[('стак.', 'стак.'), ('ст.л.', 'ст.л.'), ('чл.', 'ч.л.'), ('гр.', 'гр.'), ('кг.', 'кг.'), ('шт.', 'шт.'), ('пуч.', 'пуч.'), ('зуб.', 'зуб.'), ('щепотк.', 'щепотк.'), ('л.', 'л.'), ('мл.', 'мл.'), ('ломт.', 'ломт'), ('гол.', 'гол.'), ('вет.', 'вет.')], max_length=255),
        ),
    ]
