# Generated by Django 3.2.7 on 2022-03-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients_and_recipes', '0003_auto_20220329_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='bigspoon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='cup250sm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='littlespoon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='onepiece',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
