# Generated by Django 3.2.7 on 2022-02-28 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients_and_recipes', '0003_auto_20220226_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='calories_per_100_gr',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='carbohydrates_per_100_gr',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fat_per_100_gr',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='protein_per_100_gr',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='for_how_many_persons',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
