# Generated by Django 3.2.7 on 2022-03-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients_and_recipes', '0004_auto_20220228_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='eng_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
