# Generated by Django 3.2.7 on 2022-04-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients_and_recipes', '0005_auto_20220330_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='data',
            field=models.TimeField(),
        ),
    ]
