# Generated by Django 3.2.7 on 2022-03-06 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients_and_recipes', '0005_recipe_eng_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient_quantity',
        ),
    ]
