# Generated by Django 3.2.7 on 2022-03-06 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients_and_recipes', '0009_alter_recipe_ingredient_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingredients_and_recipes.recipecategory'),
        ),
    ]
